### ISSUE TITLE
this is amazing, could you please tell me how to generate this?

### ISSUE THREAD

**Issue by liamxg** [stephaneguindon/stephaneguindon.github.io#10]
<img width="1215" alt="image" src="https://github.com/stephaneguindon/stephaneguindon.github.io/assets/46078579/df80a35f-be8d-4a06-a98c-68c60afe8c59">

**Comment by liamxg** [comment]
<img width="780" alt="image" src="https://github.com/stephaneguindon/stephaneguindon.github.io/assets/46078579/9ffbd7ca-ba5a-4663-b995-d543be535c5c">

**Comment by liamxg** [comment]
<img width="1138" alt="image" src="https://github.com/stephaneguindon/stephaneguindon.github.io/assets/46078579/1bb86e5d-79d7-4d7d-b6be-823d6ec33170">

**Comment by BEAST-Community** [comment]
Dear @stephaneguindon,
Hope you can reply to me, thanks.
